version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pacagroup-sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=YourStrong!Passw0rd123
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Pacagroup.Ecommerce.Services.WebApi/Dockerfile
    container_name: pacagroup-api
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      ConnectionStrings__NorthwindConnection: "Server=sqlserver,1433;Database=Northwind;Encrypt=True;TrustServerCertificate=True"
      Jwt__Issuer: "Pacagroup.Ecommerce"
      Jwt__Audience: "Pacagroup.Ecommerce.Users"
      Jwt__Key: "MySecretKeyForJWTTokenGeneration123456789"
    ports:
      - "7087:8080"
    # opcional: si quieres ver los logs en la consola
    # logging:
    #   driver: "json-file"

volumes:
  sql-data: